CREATE TABLE Seasonals (
    seasons INTEGER,
    titleswon INTEGER,
    leaguewins INTEGER,
    divswon1 INTEGER,
    divswon2 INTEGER,
    divswon3 INTEGER,
    divswon4 INTEGER,
    promotions INTEGER,
    holds INTEGER,
    relegations INTEGER,
    rankingpoints INTEGER,
    bestdivision INTEGER,
    bestpoints INTEGER,
    starlevel INTEGER,
    alltimegoals INTEGER,
    alltimegoalsagainst INTEGER,
    skill INTEGER,
    wins INTEGER,
    ties INTEGER,
    losses INTEGER,
    currentdivision INTEGER,
    totalgames INTEGER,
    clubid INTEGER NOT NULL,
    createdAt TEXT,
    updatedAt TEXT
);