CREATE TABLE Players (
    name TEXT NOT NULL,
    gamesPlayed TEXT NOT NULL,
    winRate TEXT NOT NULL,
    goals TEXT NOT NULL,
    assists TEXT NOT NULL,
    cleanSheetsDef TEXT NOT NULL,
    cleanSheetsGK TEXT NOT NULL,
    shotSuccessRate TEXT NOT NULL,
    passesMade TEXT NOT NULL,
    passSuccessRate TEXT NOT NULL,
    tacklesMade TEXT NOT NULL,
    tackleSuccessRate TEXT NOT NULL,
    proName TEXT NOT NULL,
    proPos TEXT NOT NULL,
    proStyle TEXT NOT NULL,
    proHeight TEXT NOT NULL,
    proNationality TEXT NOT NULL,
    proOverall TEXT NOT NULL,
    manOfTheMatch TEXT NOT NULL,
    redCards TEXT NOT NULL,
    favoritePosition TEXT NOT NULL,
    createdAt TEXT NOT NULL,
    updatedAt TEXT NOT NULL,
    clubid INTEGER
);